name = "ViewTree ($mol)"
grammar = "molviewtree"
path_suffixes = ["view.tree"]
line_comments = ["//"]
language_servers = ["view-tree-lsp"]
tab_size = 1
hard_tabs = true

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]